// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DevToolsManage","status":true,"description":"デベロッパツール管理プラグイン","parameters":{"開始時に起動":"ON","常に前面表示":"OFF","デベロッパツール表示位置":"0,0,800,600","最小化切替キー":"F8","リロードキー":"F12","画面の左寄せキー":"","高速化切替キー":"","強制戦闘勝利キー":"","スクリプト実行キー":"","フリーズキー":"","FPS表示":"OFF","タイトルカット":"ON","高速開始":"OFF","高速スピード":"2","モバイル偽装":"OFF","メニューバー表示":"ON","クリックメニュー":"2"}},
{"name":"QuasiMovement","status":true,"description":"Change the way movement works.","parameters":{"Grid":"1","Off Grid":"true","Tile Size":"48","=====================":"","Smart Move":"3","Old Smart Move Dir":"false","Mid Pass":"false","Move On Click":"false","Diagonal":"true","Diagonal Speed":"0","Collision":"#ff0000","Water Collision":"#00ff00","Deep Water Collision":"#0000ff","Collision Map Scan":"4","Water Terrain Tag":"1","Deep Water Terrain Tag":"2","Player Box":"60, 48, -4, 0","Event Box":"48, 48, 0, 6","Boat Box":"36, 24, 6, 12","Ship Box":"36, 24, 6, 24","Airship Box":"36, 36, 6, 6","JSON folder":"data/","Collision Map folder":"img/parallaxes/","Region Map folder":"img/parallaxes/","Use Regions Boxes":"false","Show Boxes":"true"}},
{"name":"HIME_PlaceholderStates","status":true,"description":"v1.0 - allows you to create a state that may resolve to a different\r\nstate when it is added or removed.","parameters":{}},
{"name":"HIME_OverridingStates","status":true,"description":"Allows you to create states that will remove other states\r\nwhen the state is added","parameters":{}},
{"name":"YED_RetainStatesOnDeath","status":true,"description":"キャラクターの死後も、アクターのステートを維持させます","parameters":{}},
{"name":"BOB_EnhancedRestrictions","status":true,"description":"Version 1.5.3 - Allows greater restrictions to be placed on\r\nweapons, armor, skills, items, and skill types.","parameters":{}},
{"name":"TMOmitEquipCommand","status":true,"description":"装備シーンからコマンドウィンドウを削除し、\nスロットウィンドウに２行分のスペースを追加します。","parameters":{}},
{"name":"SupponShopStock","status":true,"description":"在庫システムを有するお店を設定します。version 1.02","parameters":{"Label of stock Number":"在庫数","Label of sold out":"売り切れ"}}
];
